mainSections = ["post"]
rssFullContent = true
favicon = "img/my_avatar.jpg"

[sidebar]
    # emoji = "📝"
    avatar = "img/my_avatar.jpg"

[footer]
    since = 2026

[article]
    [article.license]
        enabled = true
        default = "本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议。转载请注明来源 逐马！"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = true
    provider = "giscus"

    [comments.giscus]
        repo             = "beilu-zhuma/beilu-zhuma.github.io"
        repoID           = "R_kgDOSwx7sg"
        category         = "Announcements"
        categoryID       = "DIC_kwDOSwx7ss4C-iVw"
        mapping          = "pathname"
        strict           = 0
        reactionsEnabled = 1
        emitMetadata     = 0
        inputPosition    = "bottom"
        lightTheme       = "light"
        darkTheme        = "dark_dimmed"
        lang             = "zh-CN"
        loading          = "lazy"
